sudo: required # means super permission
language: generic

services:
  - docker # will install docker

before_install:
  - docker build -t jadensiow/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true USERNAME/docker-react npm run test
