language: generic
sudo: required # means super permission

services:
  - docker # will install docker

before_install:
  - docker build -t jadensiow/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jadensiow/docker-react npm run test
